### PR TITLE
Upgrade core foundation to 0.5

### PR DESCRIPTION
**Pull request by faern**
There is a new version of `core-foundation` out. And it provides some extra convenience stuff, so nice to upgrade.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/system-configuration-rs/5)

### CODE REVIEW

**Comment by faern** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[system-configuration/Cargo.toml, line 13 at r1](https://reviewable.io:443/reviews/mullvad/system-configuration-rs/5#-L457P5_PXc-42J2h4eW:-L457P5_PXc-42J2h4eX:b-4lmg6g) ([raw file](https://github.com/mullvad/system-configuration-rs/blob/cfda5c348acbbc9ca9c9f621c29d2661604b4af9/system-configuration/Cargo.toml#L13)):*
> ```TOML
> [dependencies]
> core-foundation = "0.4.6"
> core-foundation-sys = "0.4.6"
> ```

No need to depend on `core-foundation-sys` directly if we depend on `core-foundation`, as the stuff needed from `-sys` are re-exported from the crate above.

---

*[system-configuration/src/dynamic_store.rs, line 145 at r1](https://reviewable.io:443/reviews/mullvad/system-configuration-rs/5#-L457_9kKjl9GD2RRzgI:-L457_9kKjl9GD2RRzgJ:b23shgl) ([raw file](https://github.com/mullvad/system-configuration-rs/blob/cfda5c348acbbc9ca9c9f621c29d2661604b4af9/system-configuration/src/dynamic_store.rs#L145)):*
> ```Rust
>     fn drop(&mut self) {
>         unsafe { CFRelease(self.as_CFTypeRef()) }
>     }
> ```

Since all CF types have the exact same struct declaration and `Drop` impl we added a macro for this in `core-foundation`.

---

*[system-configuration/src/bin/set_dns.rs, line 21 at r1](https://reviewable.io:443/reviews/mullvad/system-configuration-rs/5#-L457k3CbRG_KSx_XYy1:-L457k3CbRG_KSx_XYy2:b2kujem) ([raw file](https://github.com/mullvad/system-configuration-rs/blob/c87a3a0a9b1f803813718c15f98779ce581d64d6/system-configuration/src/bin/set_dns.rs#L21)):*
> ```Rust
>             .get("State:/Network/Global/IPv4")
>             .expect("Unable to find global settings")
>             .downcast_into::<CFDictionary>()
> ```

New types of casting allows getting rid of the `_` generic type, as well as a new `_into` version that is consuming and more efficient.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/system-configuration-rs/5)*

**Comment by pronebird** [comment]
Reviewed 1 of 7 files at r1.
Review status: 1 of 7 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/system-configuration-rs/5)*

**Comment by pronebird** [comment]
Reviewed 2 of 7 files at r1.
Review status: 3 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[system-configuration/Cargo.toml, line 13 at r1](https://reviewable.io:443/reviews/mullvad/system-configuration-rs/5#-L457P5_PXc-42J2h4eW:-L45Y_eKs5kvriIwAIWx:b-ot4b68) ([raw file](https://github.com/mullvad/system-configuration-rs/blob/cfda5c348acbbc9ca9c9f621c29d2661604b4af9/system-configuration/Cargo.toml#L13)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

No need to depend on `core-foundation-sys` directly if we depend on `core-foundation`, as the stuff needed from `-sys` are re-exported from the crate above.
</blockquote></details>

Good news!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/system-configuration-rs/5)*

**Comment by pronebird** [comment]
Reviewed 1 of 7 files at r1.
Review status: 4 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[system-configuration/src/dynamic_store.rs, line 145 at r1](https://reviewable.io:443/reviews/mullvad/system-configuration-rs/5#-L457_9kKjl9GD2RRzgI:-L45ZDonDMYLdjlFMSLr:b24dgcf) ([raw file](https://github.com/mullvad/system-configuration-rs/blob/cfda5c348acbbc9ca9c9f621c29d2661604b4af9/system-configuration/src/dynamic_store.rs#L145)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Since all CF types have the exact same struct declaration and `Drop` impl we added a macro for this in `core-foundation`.
</blockquote></details>

Alright. The new macro looks a little cryptic but as long as it works I guess :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/system-configuration-rs/5)*

**Comment by pronebird** [comment]
Reviewed 3 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/system-configuration-rs/5)*

**Comment by pronebird** [comment]
Little adjustments. Looks good!

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/system-configuration-rs/5#-:-L45_4-InZhLF17m15il:b-cphvej)*

**Pull request merged**
