### PR TITLE
Remove deprecated IrDA variant and private _kSCNetworkInterfaceTypeBridge reference

### LINKED ISSUE #41: Undefined symbols when archiving (release build) on iOS
I just came across this error when compiling a release build for iOS:

```
Undefined symbols for architecture arm64:
  "_kSCNetworkInterfaceTypeIrDA", referenced from:
      system_configuration::network_configuration::SCNetworkInterfaceType::from_cfstring::h2e804825311d5049 in libsos_native_bindings_static.a(system_configuration-f1f2543c1b6493c9.system_configuration.5fa3ee70-cgu.0.rcgu.o)
```

I am using this library as a transient dependency via `if-watch` and I wonder what the correct way to fix this is.

The [documentation](https://developer.apple.com/documentation/systemconfiguration/kscnetworkinterfacetypeirda) states that the field is deprecated and no longer exists after MacOS 12.0 what I don't understand is why it is affecting my iOS build (the MacOS build continues to work as expected).

Any ideas?

### PR DESCRIPTION
**Pull request by tmpfs**
Fixes for publishing iOS apps that have `system-configuration` in their dependency tree.

Closes #41 and closes #39.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/system-configuration-rs/42)

### CODE REVIEW

**Comment by dignifiedquire** [comment]
any chance of this merging? running into this problem as well

**Comment by dignifiedquire** [comment]
ping

**Comment by tmpfs** [comment]
Thanks @dignifiedquire for the reminder it sure would be nice to remove this from my `patch.crates-io`.

@faern and @dlon - is it possible to get a review and merge here please?

**Comment by dlon** [comment]
@tmpfs #43 has been merged, which should address this.

**Pull request closed without merging**
