### PR TITLE
Fix clippy failing CI.

### PR DESCRIPTION
**Pull request by mstyura**
Noticed that after my MR merged the CI is failing, hopefully this fixed it.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/system-configuration-rs/56)

### CODE REVIEW

**Comment by mstyura** [comment]
@faern this MR should probably fix CI on main branch. At least locally `cargo clippy --all-features --all-targets` succeed now.

**Comment by faern** [comment]
I noticed `cargo test` failed on `main` even before your PR also.

**Comment by faern** [comment]
`cargo test` is still failing for me. From what I can tell `test_service_order` still fails. Does it pass for you locally?

**Comment by mstyura** [comment]
On my local machine tests are "green":
```

running 10 tests
test network_configuration::test::test_empty_array ... ok
test preferences::tests::retain_count ... ok
test network_configuration::test::test_service_order ... ok
test network_reachability::test::test_network_reachability_from_addr ... ok
test network_reachability::test::test_reachability_ref_from_host ... ok
test network_reachability::test::test_sockaddr_pair_reachability ... ok
test network_reachability::test::test_sockaddr_local_to_dns_google_pair_reachability ... ok
test network_configuration::test::test_get_all_interfaces ... ok
test network_configuration::test::test_get_type ... ok
test network_reachability::test::assert_infallibility_of_setting_a_callback ... ok

test result: ok. 10 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.01s


running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

```
```
cargo check --all --tests --examples --bins
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.08s
```

```
cargo clippy --all-features --all-targets 
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.11s
```

**Review by faern — APPROVED** [review]

**Comment by faern** [comment]
Ok! Not for me, but your changes also does not make anything worse. The cfg stuff is indeed something we should be updating. So let's merge this, even if the tests still fail for me locally.

**Comment by mstyura** [comment]
Seems the last problem is:
```
Error: Resource not accessible by integration
```
which seems to be the problem with gitlab ci job itself.

**Comment by faern** [comment]
Yes indeed. I'm working on that in #57

**Pull request merged**
