### PR TITLE
Add get_keys method to SCDynamicStore

### PR DESCRIPTION
**Pull request by faern**
I had to list all keys for DNS settings, so I had to add this.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/system-configuration-rs/4)

### CODE REVIEW

**Comment by pronebird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[system-configuration/src/dynamic_store.rs, line 183 at r1](https://reviewable.io:443/reviews/mullvad/system-configuration-rs/4#-L-DDRBUHTfD_EXEtSSO:-L-DDRBUHTfD_EXEtSSP:b-qqino) ([raw file](https://github.com/mullvad/system-configuration-rs/blob/2577b8d35941b3cfa3d7a9f2a699c4767fac2082/system-configuration/src/dynamic_store.rs#L183)):*
> ```Rust
>             );
>             if array_ref != ptr::null() {
>                 Some(CFArray::wrap_under_create_rule(array_ref))
> ```

Returned array should be released by the receiver so if I get it right `wrap_under_create_rule` should release the ref once it goes out of bounds. I hope it does not do extra `retain()` call.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/system-configuration-rs/4)*

**Comment by pronebird** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[system-configuration/src/dynamic_store.rs, line 183 at r1](https://reviewable.io:443/reviews/mullvad/system-configuration-rs/4#-L-DDRBUHTfD_EXEtSSO:-L-DE3prdPTUMgmVv7hk:b-pvkx7e) ([raw file](https://github.com/mullvad/system-configuration-rs/blob/2577b8d35941b3cfa3d7a9f2a699c4767fac2082/system-configuration/src/dynamic_store.rs#L183)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Returned array should be released by the receiver so if I get it right `wrap_under_create_rule` should release the ref once it goes out of bounds. I hope it does not do extra `retain()` call.
</blockquote></details>

OK docs say "The reference count is not bumped"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/system-configuration-rs/4)*

**Comment by pronebird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/system-configuration-rs/4#-:-L-DE96wzVVmYQg_88FU:bnfp4nl)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[system-configuration/src/dynamic_store.rs, line 183 at r1](https://reviewable.io:443/reviews/mullvad/system-configuration-rs/4#-L-DDRBUHTfD_EXEtSSO:-L-DKeOlq-bHdPSZO1VJ:bgey62y) ([raw file](https://github.com/mullvad/system-configuration-rs/blob/2577b8d35941b3cfa3d7a9f2a699c4767fac2082/system-configuration/src/dynamic_store.rs#L183)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

OK docs say "The reference count is not bumped"
</blockquote></details>

Yes. The `core-foundation` bindings works as following: every CF type has two constructors:
* `wrap_under_create_rule` - Takes the pointer and does nothing, until drop, then it calls `CFRelease`
* `wrap_under_get_rule` - calls `CFRetain` on the pointer and then calls `wrap_under_create_rule`.

So yes. With both constructors the retain count will be decremented on drop, but only the get constructor retains on construction.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/system-configuration-rs/4)*

**Pull request merged**
