### PR TITLE
Commit generated bindings

### PR DESCRIPTION
**Pull request by faern**
It's troublesome to require anyone who wish to build this crate to also have the macOS SDK and the Xcode CLI tools installed, as discussed in the `pfctl` PR some time ago.

This does the equivalent to this crate. Moves the bindgen call from `build.rs` to a separate `generate_bindings.rs` that can be used to manually update the bindings if that would ever become needed.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/system-configuration-rs/6)

### CODE REVIEW

**Comment by faern** [comment]
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[generate_bindings.sh, line 5 at r1](https://reviewable.io:443/reviews/mullvad/system-configuration-rs/6#-L4ANln8x8OpaqFU1-Ub:-L4ANln9s3LrDFJuX98v:bwgmwxt) ([raw file](https://github.com/mullvad/system-configuration-rs/blob/c26efe633453e6003dc208ce8b8875ad74862938/generate_bindings.sh#L5)):*
> ```Shell
> # Always have the latest version of bindgen and rustfmt installed before using this script
> 
> export DYLD_LIBRARY_PATH=$(rustc +stable --print sysroot)/lib
> ```

This is maybe not optimal. But I had trouble getting it to work without this. The problem here is partly due to the `+stable` part. This won't work if your installed bindgen is built against some other toolchain than your stable. But it works for now. Can hopefully be done better when bindgen is shipped in a more stable way.

---

*[system-configuration-sys/Cargo.toml, line 10 at r1](https://reviewable.io:443/reviews/mullvad/system-configuration-rs/6#-L4AO31k4au_-KBjImDx:-L4AO31k4au_-KBjImDy:b2jhg9l) ([raw file](https://github.com/mullvad/system-configuration-rs/blob/df96c5cd93680f4d3faaddd69a42f99c9e5b54ab/system-configuration-sys/Cargo.toml#L10)):*
> ```TOML
> repository = "https://github.com/mullvad/system-configuration-rs"
> license = "MIT/Apache-2.0"
> build = "build.rs"
> ```

As you can see, we still have a `build.rs` build script. But since a couple of Cargo versions ago this directive is not needed. If there is a `build.rs` file in the crate root then it will automatically be executed as the build script.. A bit magical maybe, but I'm not the one who decided that part.

---

*[system-configuration-sys/src/dynamic_store.rs, line 18 at r1](https://reviewable.io:443/reviews/mullvad/system-configuration-rs/6#-L4AOPMR3y1aB_qNU3n0:-L4AOPMSNnAmjgFHIQ2s:bnqii5n) ([raw file](https://github.com/mullvad/system-configuration-rs/blob/c26efe633453e6003dc208ce8b8875ad74862938/system-configuration-sys/src/dynamic_store.rs#L18)):*
> ```Rust
> #[derive(Debug, Copy, Clone)]
> pub struct dispatch_queue_s {
>     pub _address: u8,
> ```

These `dispatch_queue_[st]` types are not really part of the dynamic store at all. They are part of the core dispatch header files. but they are not available anywhere else from what I could find, so I had to keep them here. If I have time at some point I might create a PR towards `libc` to add them to the darwin builds there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/system-configuration-rs/6)*

**Comment by pronebird** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[system-configuration-sys/src/dynamic_store.rs, line 18 at r1](https://beta.reviewable.io/reviews/mullvad/system-configuration-rs/6#-L4AOPMR3y1aB_qNU3n0:-L4AaLlx6DqgT7ymjC4w:beocjcm) ([raw file](https://github.com/mullvad/system-configuration-rs/blob/c26efe633453e6003dc208ce8b8875ad74862938/system-configuration-sys/src/dynamic_store.rs#L18)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

These `dispatch_queue_[st]` types are not really part of the dynamic store at all. They are part of the core dispatch header files. but they are not available anywhere else from what I could find, so I had to keep them here. If I have time at some point I might create a PR towards `libc` to add them to the darwin builds there.
</blockquote></details>

Because they are macro generated in `/usr/include/dispatch/queue.h` which is a part of `libdispatch`. I doubt that `libc` has anything to do with such bindings.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/system-configuration-rs/6)*

**Comment by pronebird** [comment]
Reviewed 1 of 8 files at r1.
Review status: 1 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[system-configuration-sys/Cargo.toml, line 10 at r1](https://beta.reviewable.io/reviews/mullvad/system-configuration-rs/6#-L4AO31k4au_-KBjImDx:-L4AdE5w2u46JNLEYY6n:b-5ot3o1) ([raw file](https://github.com/mullvad/system-configuration-rs/blob/df96c5cd93680f4d3faaddd69a42f99c9e5b54ab/system-configuration-sys/Cargo.toml#L10)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

As you can see, we still have a `build.rs` build script. But since a couple of Cargo versions ago this directive is not needed. If there is a `build.rs` file in the crate root then it will automatically be executed as the build script.. A bit magical maybe, but I'm not the one who decided that part.
</blockquote></details>

Cargo always had defaults, it seems they extended them to build scripts now so let's stick to it :)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/system-configuration-rs/6)*

**Comment by pronebird** [comment]
Review status: 1 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[system-configuration-sys/src/dynamic_store.rs, line 18 at r1](https://beta.reviewable.io/reviews/mullvad/system-configuration-rs/6#-L4AOPMR3y1aB_qNU3n0:-L4AeHHC1_Ygx8JhZMbh:b-b8dlqj) ([raw file](https://github.com/mullvad/system-configuration-rs/blob/c26efe633453e6003dc208ce8b8875ad74862938/system-configuration-sys/src/dynamic_store.rs#L18)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Because they are macro generated in `/usr/include/dispatch/queue.h` which is a part of `libdispatch`. I doubt that `libc` has anything to do with such bindings.
</blockquote></details>

was there anything that bothered you regarding importing those with bindgen or it didn't work?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/system-configuration-rs/6)*

**Comment by pronebird** [comment]
Review status: 1 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[system-configuration-sys/src/dynamic_store.rs, line 18 at r1](https://beta.reviewable.io/reviews/mullvad/system-configuration-rs/6#-L4AOPMR3y1aB_qNU3n0:-L4Aera65LQlxfnpLism:b-ohlv4d) ([raw file](https://github.com/mullvad/system-configuration-rs/blob/c26efe633453e6003dc208ce8b8875ad74862938/system-configuration-sys/src/dynamic_store.rs#L18)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

was there anything that bothered you regarding importing those with bindgen or it didn't work?
</blockquote></details>

Ah hold on I am looking at the generated file am I :laughing: 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/system-configuration-rs/6)*

**Comment by faern** [comment]
Review status: 1 of 8 files reviewed at latest revision, all discussions resolved.

---

*[system-configuration-sys/src/dynamic_store.rs, line 18 at r1](https://reviewable.io:443/reviews/mullvad/system-configuration-rs/6#-L4AOPMR3y1aB_qNU3n0:-L4AeXVxQ4ETd7TLzJ1j:bckar38) ([raw file](https://github.com/mullvad/system-configuration-rs/blob/c26efe633453e6003dc208ce8b8875ad74862938/system-configuration-sys/src/dynamic_store.rs#L18)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Ah hold on I am looking at the generated file am I :laughing: 
</blockquote></details>

Yup, I know where they come from. These macros are what bindgen use here to generate the struct. Not sure if it does it correctly or not though, I have not seen the C equivalent since it's so many layers of macros.

Anyhow, the description for libc is: "A Rust library with native bindings to the types and functions commonly found on various systems, including libc.". So they do include a lot of stuff that is not strictly libc. But that is a different issue, because I'm not going to put work into making this go into libc now anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/system-configuration-rs/6)*

**Comment by pronebird** [comment]
Review status: 1 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[system-configuration-sys/src/dynamic_store.rs, line 18 at r1](https://beta.reviewable.io/reviews/mullvad/system-configuration-rs/6#-L4AOPMR3y1aB_qNU3n0:-L4AfSr992dixkC-T9Hk:bl7i9rb) ([raw file](https://github.com/mullvad/system-configuration-rs/blob/c26efe633453e6003dc208ce8b8875ad74862938/system-configuration-sys/src/dynamic_store.rs#L18)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Yup, I know where they come from. These macros are what bindgen use here to generate the struct. Not sure if it does it correctly or not though, I have not seen the C equivalent since it's so many layers of macros.

Anyhow, the description for libc is: "A Rust library with native bindings to the types and functions commonly found on various systems, including libc.". So they do include a lot of stuff that is not strictly libc. But that is a different issue, because I'm not going to put work into making this go into libc now anyway.
</blockquote></details>

Well `dispatch_queue_t` is a `NSObject`. So those are actually Objective-C classes. 

Rough representation of object in Objective-C is:

```
typedef struct objc_object {
    struct objc_class * isa;
} *id;
```

`u8` for address seems wrong?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/system-configuration-rs/6)*

**Comment by pronebird** [comment]
Review status: 1 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[system-configuration-sys/src/dynamic_store.rs, line 18 at r1](https://beta.reviewable.io/reviews/mullvad/system-configuration-rs/6#-L4AOPMR3y1aB_qNU3n0:-L4Am4Gf1_zT7zP-aVvu:b-ai0uag) ([raw file](https://github.com/mullvad/system-configuration-rs/blob/c26efe633453e6003dc208ce8b8875ad74862938/system-configuration-sys/src/dynamic_store.rs#L18)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Well `dispatch_queue_t` is a `NSObject`. So those are actually Objective-C classes. 

Rough representation of object in Objective-C is:

```
typedef struct objc_object {
    struct objc_class * isa;
} *id;
```

`u8` for address seems wrong?
</blockquote></details>

However since dispatch_queue_t is actually a pointer and we never inspect its guts I think it's fine. I don't know why it bothered to generate the `*_s` part, the raw void pointer would be totally fine.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/system-configuration-rs/6)*

**Comment by pronebird** [comment]
Reviewed 7 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/system-configuration-rs/6)*

**Comment by pronebird** [comment]
Looks good to me

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/system-configuration-rs/6#-:-L4AoHCx06Dcc1_ROzcI:b-owaf1x)*

**Comment by faern** [comment]
Review status: 6 of 8 files reviewed at latest revision, all discussions resolved.

---

*[system-configuration-sys/src/dynamic_store.rs, line 18 at r1](https://reviewable.io:443/reviews/mullvad/system-configuration-rs/6#-L4AOPMR3y1aB_qNU3n0:-L4CDcWWaeqt8yBVGldA:bilnd6m) ([raw file](https://github.com/mullvad/system-configuration-rs/blob/c26efe633453e6003dc208ce8b8875ad74862938/system-configuration-sys/src/dynamic_store.rs#L18)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

However since dispatch_queue_t is actually a pointer and we never inspect its guts I think it's fine. I don't know why it bothered to generate the `*_s` part, the raw void pointer would be totally fine.
</blockquote></details>

As per your recommendation I blacklisted the type from being generated and inserted a manual void pointer instead. Should suffice for now. Might have to be changed out if anyone ever want to call `SCDynamicStoreSetDispatchQueue`, but that is a later problem.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/system-configuration-rs/6)*

**Comment by faern** [comment]
Review status: 5 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[system-configuration/Cargo.toml, line 7 at r2](https://reviewable.io:443/reviews/mullvad/system-configuration-rs/6#-L4CHCUMGBAOywADE9kB:-L4CHCUMGBAOywADE9kC:bwqe9mz) ([raw file](https://github.com/mullvad/system-configuration-rs/blob/736e785ad61a2d39036b561946f1c739f2143560/system-configuration/Cargo.toml#L7)):*
> ```TOML
> description = "Bindings to SystemConfiguration framework for macOS"
> keywords = ["macos", "system", "configuration", "bindings"]
> categories = ["api-bindings", "os::macos-apis"]
> ```

Since I want to release this really soon I looked over the metadata and found I could improve the categories. When reading the descriptions at https://crates.io/categories I realized I should not have both `api-bindings` and `external-ffi-bindings` on the same crate. One is for safe and idiomatic Rust wrappers and one is for low level bindings. So I have one of the categories on each crate now instead. Plus adding `os::macos-apis` to both since they are both macOS specific APIs (same API, different abstraction level)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/system-configuration-rs/6)*

**Comment by pronebird** [comment]
Review status: 5 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[system-configuration/Cargo.toml, line 7 at r2](https://reviewable.io:443/reviews/mullvad/system-configuration-rs/6#-L4CHCUMGBAOywADE9kB:-L4FuUDPcstqmACyYURg:b1ubcge) ([raw file](https://github.com/mullvad/system-configuration-rs/blob/736e785ad61a2d39036b561946f1c739f2143560/system-configuration/Cargo.toml#L7)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Since I want to release this really soon I looked over the metadata and found I could improve the categories. When reading the descriptions at https://crates.io/categories I realized I should not have both `api-bindings` and `external-ffi-bindings` on the same crate. One is for safe and idiomatic Rust wrappers and one is for low level bindings. So I have one of the categories on each crate now instead. Plus adding `os::macos-apis` to both since they are both macOS specific APIs (same API, different abstraction level)
</blockquote></details>

Makes sense

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/system-configuration-rs/6)*

**Comment by pronebird** [comment]
Review status: 5 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[system-configuration-sys/src/dynamic_store.rs, line 18 at r1](https://reviewable.io:443/reviews/mullvad/system-configuration-rs/6#-L4AOPMR3y1aB_qNU3n0:-L4FuZma2N6Wkq60fdOd:bn0u256) ([raw file](https://github.com/mullvad/system-configuration-rs/blob/c26efe633453e6003dc208ce8b8875ad74862938/system-configuration-sys/src/dynamic_store.rs#L18)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

As per your recommendation I blacklisted the type from being generated and inserted a manual void pointer instead. Should suffice for now. Might have to be changed out if anyone ever want to call `SCDynamicStoreSetDispatchQueue`, but that is a later problem.
</blockquote></details>

Exactly. The part of the deal with DispatchQueue that we need to be able to create them first, but since there are no bindings for that there is little t no point to have anything but an opaque pointer. 

It would be good to address this but that sounds like an entirely separate venture. Good work Linus :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/system-configuration-rs/6)*

**Comment by pronebird** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/system-configuration-rs/6)*

**Comment by pronebird** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/system-configuration-rs/6#-:-L4FvIE17mX9AG1nizXC:bnfp4nl)*

**Pull request merged**
