### PR TITLE
Fix memory leak in SCNetworkReachability::set_callback

### LINKED ISSUE #34: Memory Leak in `SCNetworkReachability::set_callback`
I believe the following code in network_reachability.rs introduces a memory leak.

https://github.com/mullvad/system-configuration-rs/blob/1bc323a12552359f5e26b56d52aa29b3449c09ec/system-configuration/src/network_reachability.rs#L239-L254

`callback` is an `Arc` holding a `NetworkReachabilityCallbackContext`, which holds a reference counted `SCNetworkReachabability` object and the capture of the callback function. `callback` is then passed into `Arc::into_raw` but there is never a matching call to `Arc::from_raw`.

I believe we need to call `Arc::from_raw` once on that pointer to ensure that the memory allocated for `NetworkReachabilityCallbackContext::new` is freed.

### PR DESCRIPTION
**Pull request by schultetwin1**
In SCNetworkReachability::set_callback, an Arc is created called `callback` and then leaked via 'into_raw`. This leak is never fixed causing a memory leak.

The fix is to rely on SCNetworkReachabilitySetCallback to call `retain` once and then `release` once when the reference is released via CFRelease.

This allows us to drop the `Arc` in `set_callback` while ensuring the reference count for that `Arc` is >0.

Fixes #34

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/system-configuration-rs/36)

### CODE REVIEW

**Review by pronebird — APPROVED** [review]
Looks good 👍

**Comment by schultetwin1** [comment]
> Where are the releases made on drop?

Are you asking, where is `CFRelease` called on the drop of `SCNetworkReachability`? Since, `SCNetworkReachability` is declared using the `declare_TCFType` macro, the drop implementation automatically calls `CFRelease`.

Or are you asking, where is the `release` function pointer called when `SCNetworkReachability` is dropped? That occurs in  [`__SCNetworkReachabilityDeallocate`](https://opensource.apple.com/source/configd/configd-1109.60.2/SystemConfiguration.fproj/SCNetworkReachability.c.auto.html).

```c
if (targetPrivate->rlsContext.release != NULL) {
    (*targetPrivate->rlsContext.release)(targetPrivate->rlsContext.info);
}
```
> Will we guarantee then that we never call decrement_strong_count on an already released Arc for example?

I believe that since the first call to `increment_strong_count` matches with the last call to `decrement_strong_count` which should never run into a scenario where a panic would cause us to call `decrement_strong_count` on an invalid Arc.

**Comment by pronebird** [comment]
> Where are the releases made on drop? My main concern is what if something panics, making drop implementations run. Will we guarantee then that we never call `decrement_strong_count` on an already released `Arc` for example? Just want to make sure we have no code path that can trigger invalid memory access.

Does panic cause `Drop` to trigger on `Arc` disregarding its underlying reference counter? Otherwise `CFRelease(self.0)`  should call `release_context` to balance the `retain_context` triggered during `SCNetworkReachabilitySetCallback()`.

**Comment by dlon** [comment]
According to the [docs](https://doc.rust-lang.org/std/sync/struct.Arc.html#method.decrement_strong_count), `Arc::decrement_strong_count` and `Arc::increment_strong_count` must be called on a raw pointer acquired through `Arc::into_raw`, not `Arc::as_ptr`. I assume this is to decrement the ref count, as it is incremented by `SCNetworkReachabilitySetCallback`?

If that's the case, I think it would be less hacky to explicitly call `Arc::decrement_strong_count` after `SCNetworkReachabilitySetCallback`, as it makes fewer assumptions about `Arc`'s implementation details.

Other than that, I'm convinced that the code is fine.

**Review by dlon — APPROVED** [review]

**Pull request merged**
